---
title: "Additional Insights"
output: html_notebook
---



Model Matrix:

```{r}
model.matrix(Percent_Bachelors~Rural_urban_code,data=full_county_table)
```



Linear Regression Models:

```{r lin_models}
income_model <- lm(Percent_Bachelors~Median_Household_Income_2019,data=full_county_table)
summary(income_model)

growth_model <- lm(Percent_Bachelors~avg_decade_growth_rate,data=full_county_table)
summary(growth_model)

poverty_model <- lm(Percent_Bachelors~Percent_Poverty,data=full_county_table)
summary(poverty_model)


```

The greatest single indicator of county-level education that we examined is median income. According to the linear model I created, median income accounts for 50.76% of the variation among counties in percentage of people receiving a bachelors degree. 


```{r lin_models_diploma}
income_no_diploma_model <- lm(Median_Household_Income_2019~Percent_No_Diploma,data=inc_edu_county)
summary(income_no_diploma_model)

percent_bach_no_diploma_model <- lm(Percent_No_Diploma~Percent_Bachelors,data=inc_edu_county)
summary(percent_bach_no_diploma_model)

percent_bach_no_diploma_model <- lm(Percent_No_Diploma~Percent_Bachelors,data=inc_edu_county)
summary(percent_bach_no_diploma_model)
```


Multiple Linear Regression Models:

```{r multi_models}
multi_model <- lm(Percent_Bachelors~Median_Household_Income_2019+avg_decade_growth_rate+Percent_Poverty,data=full_county_table)
summary(multi_model)

```

```{r density_plot_bach}
densityPlot(inc_edu_county$Percent_Bachelors, "Density Plot", "Percent Bachelors")
```
  