#Execute this module after the "Public Vs Private Enrollment Countywide data.Rmd" module


#Loading the packages

```{r load_packages}
library(tidyverse)
library(readr)
library(readxl)
library(reactable)
library(scales)
library(hrbrthemes)
library(ggridges)
library(gganimate)
library(viridis)
library(gifski)
```

```{r Merging and altering table}

final_group <- group_by_urb_table %>% 
  gather(Qualification, Percentage, Percent_Bachelors:Percent_Associates)

```

#Graphs

```{r Statewise Cleaning}
library (usmap)
St_Pop <- inc_edu_state[order(inc_edu_state$Area_name),]
St_Pop <- St_Pop[!(St_Pop$Area_name == "United States"),]
St_Pop$fips <- statepop$fips 
St_Pop$abbr <- statepop$abbr

St_Pop <- St_Pop %>% 
  rename(Income = Median_Household_Income_2019) %>% 
  rename(Less_than_High_School = `Percent_No_Diploma`) %>% 
  rename ( High_School_Only = `Percent_Diploma`) %>% 
  rename(College_or_Associate = `Percent_Associates`) %>% 
  rename(Bachelors = `Percent_Bachelors`)

```

```{r Countywise Cleaning}
#anti_join(countypop, Ct_Pop, by = "fips")
Ct_Pop <- inc_edu_county[order(inc_edu_county$Area_name),]
Ct_Pop <- Ct_Pop[order(Ct_Pop$FIPS_Code),]
Ct_Pop <- na.omit(Ct_Pop)
temp1 <- countypop
temp2 <- temp1[!(temp1$fips == "15005"),]
Ct_Pop$fips <- temp2$fips
Ct_Pop$abbr <- temp2$abbr
Ct_Pop <- Ct_Pop %>% 
  rename(Income = Median_Household_Income_2019) %>% 
  rename(Less_than_High_School = `Percent_No_Diploma`) %>% 
  rename ( High_School_Only = `Percent_Diploma`) %>% 
  rename(College_or_Associate = `Percent_Associates`) %>% 
  rename(Bachelors = `Percent_Bachelors`)

```